-- StockCare MVP schema (Flyway V1). PostgreSQL 16.
-- IDs are UUIDs generated by the application layer. All timestamps are stored as timestamptz.

-- ---------------- Core organisation ----------------

CREATE TABLE depot (
    id            UUID PRIMARY KEY,
    code          VARCHAR(32)  NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    address_line  VARCHAR(255),
    region        VARCHAR(64),
    city          VARCHAR(64),
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    phone         VARCHAR(32),
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    version       BIGINT       NOT NULL
);

CREATE TABLE pharmacy (
    id             UUID PRIMARY KEY,
    code           VARCHAR(32)  NOT NULL UNIQUE,
    name           VARCHAR(255) NOT NULL,
    license_number VARCHAR(64),
    address_line   VARCHAR(255),
    region         VARCHAR(64),
    city           VARCHAR(64),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    phone          VARCHAR(32),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    version        BIGINT       NOT NULL
);

CREATE TABLE depot_pharmacy (
    id          UUID PRIMARY KEY,
    depot_id    UUID NOT NULL REFERENCES depot(id),
    pharmacy_id UUID NOT NULL REFERENCES pharmacy(id),
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    version     BIGINT NOT NULL,
    CONSTRAINT uq_depot_pharmacy UNIQUE (depot_id, pharmacy_id)
);
CREATE INDEX idx_depot_pharmacy_depot ON depot_pharmacy(depot_id);
CREATE INDEX idx_depot_pharmacy_pharmacy ON depot_pharmacy(pharmacy_id);

CREATE TABLE app_user (
    id            UUID PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    role          VARCHAR(16)  NOT NULL,
    status        VARCHAR(16)  NOT NULL,
    pharmacy_id   UUID REFERENCES pharmacy(id),
    depot_id      UUID REFERENCES depot(id),
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    version       BIGINT       NOT NULL
);
CREATE INDEX idx_user_pharmacy ON app_user(pharmacy_id);
CREATE INDEX idx_user_depot ON app_user(depot_id);

-- ---------------- Catalogue & inventory ----------------

CREATE TABLE medication (
    id                 UUID PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    generic_name       VARCHAR(255),
    dosage             VARCHAR(64),
    pharmaceutical_form VARCHAR(64),
    package_size       VARCHAR(64),
    sku                VARCHAR(64) UNIQUE,
    barcode            VARCHAR(64),
    atc_code           VARCHAR(16),
    category           VARCHAR(64),
    cold_chain         BOOLEAN NOT NULL,
    criticality_score  DOUBLE PRECISION,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255),
    version            BIGINT NOT NULL
);
CREATE INDEX idx_medication_name ON medication(name);

CREATE TABLE inventory_item (
    id                     UUID PRIMARY KEY,
    pharmacy_id            UUID NOT NULL REFERENCES pharmacy(id),
    medication_id          UUID NOT NULL REFERENCES medication(id),
    current_quantity       INTEGER NOT NULL,
    minimum_quantity       INTEGER NOT NULL,
    avg_daily_consumption  DOUBLE PRECISION NOT NULL,
    reorder_threshold      INTEGER,
    expiration_date        DATE,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,
    created_by             VARCHAR(255),
    updated_by             VARCHAR(255),
    version                BIGINT NOT NULL,
    CONSTRAINT uq_inventory_pharmacy_med UNIQUE (pharmacy_id, medication_id)
);
CREATE INDEX idx_inventory_pharmacy ON inventory_item(pharmacy_id);

CREATE TABLE stock_adjustment (
    id                UUID PRIMARY KEY,
    inventory_item_id UUID NOT NULL REFERENCES inventory_item(id),
    delta             INTEGER NOT NULL,
    quantity_before   INTEGER NOT NULL,
    quantity_after    INTEGER NOT NULL,
    reason            VARCHAR(16) NOT NULL,
    note              VARCHAR(500),
    occurred_at       TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL
);
CREATE INDEX idx_stock_adjustment_item ON stock_adjustment(inventory_item_id);

-- ---------------- Predictions ----------------

CREATE TABLE prediction_result (
    id                         UUID PRIMARY KEY,
    pharmacy_id                UUID NOT NULL REFERENCES pharmacy(id),
    medication_id              UUID NOT NULL REFERENCES medication(id),
    current_stock              INTEGER NOT NULL,
    predicted_shortage_date    DATE,
    estimated_remaining_days   INTEGER,
    predicted_missing_quantity INTEGER NOT NULL,
    confidence                 DOUBLE PRECISION,
    reason                     VARCHAR(1000),
    model_version              VARCHAR(64),
    simulated                  BOOLEAN NOT NULL,
    prediction_time            TIMESTAMPTZ NOT NULL,
    created_at                 TIMESTAMPTZ NOT NULL,
    updated_at                 TIMESTAMPTZ NOT NULL,
    created_by                 VARCHAR(255),
    updated_by                 VARCHAR(255),
    version                    BIGINT NOT NULL
);
CREATE INDEX idx_prediction_pharmacy ON prediction_result(pharmacy_id);

-- ---------------- Requests ----------------

CREATE TABLE pharmacy_request (
    id                   UUID PRIMARY KEY,
    pharmacy_id          UUID NOT NULL REFERENCES pharmacy(id),
    depot_id             UUID NOT NULL REFERENCES depot(id),
    status               VARCHAR(16) NOT NULL,
    urgency              VARCHAR(16) NOT NULL,
    notes                VARCHAR(1000),
    internal_notes       VARCHAR(1000),
    affected_patients    INTEGER,
    source_prediction_id UUID,
    submitted_at         TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    version              BIGINT NOT NULL
);
CREATE INDEX idx_request_depot ON pharmacy_request(depot_id);
CREATE INDEX idx_request_pharmacy ON pharmacy_request(pharmacy_id);
CREATE INDEX idx_request_status ON pharmacy_request(status);

CREATE TABLE pharmacy_request_item (
    id                 UUID PRIMARY KEY,
    request_id         UUID NOT NULL REFERENCES pharmacy_request(id) ON DELETE CASCADE,
    medication_id      UUID NOT NULL REFERENCES medication(id),
    requested_quantity INTEGER NOT NULL,
    note               VARCHAR(500),
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255),
    version            BIGINT NOT NULL
);
CREATE INDEX idx_request_item_request ON pharmacy_request_item(request_id);

CREATE TABLE priority_result (
    id                   UUID PRIMARY KEY,
    request_id           UUID NOT NULL UNIQUE REFERENCES pharmacy_request(id),
    coefficient          DOUBLE PRECISION NOT NULL,
    factors_json         VARCHAR(2000),
    explanation          VARCHAR(1000),
    calculation_version  VARCHAR(64),
    simulated            BOOLEAN NOT NULL,
    calculated_at        TIMESTAMPTZ NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    version              BIGINT NOT NULL
);

-- ---------------- Model traceability & simulated clock ----------------

CREATE TABLE model_execution_log (
    id             UUID PRIMARY KEY,
    model_type     VARCHAR(32) NOT NULL,
    mode           VARCHAR(16) NOT NULL,
    model_version  VARCHAR(64),
    correlation_id VARCHAR(64),
    status         VARCHAR(16) NOT NULL,
    duration_ms    BIGINT,
    input_summary  VARCHAR(1000),
    output_summary VARCHAR(1000),
    error_message  VARCHAR(500),
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    version        BIGINT NOT NULL
);
CREATE INDEX idx_model_log_type ON model_execution_log(model_type);

CREATE TABLE simulated_time_config (
    id               UUID PRIMARY KEY,
    mode             VARCHAR(16) NOT NULL,
    simulated_anchor TIMESTAMPTZ,
    real_anchor      TIMESTAMPTZ,
    frozen           BOOLEAN NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    version          BIGINT NOT NULL
);
